export const ExamsData=[
    {
        id:1,
        date : 'Wednesday,june 7th',
        time : '3:30 PM',
        courseName:'Introduction To Data Analysis',
        instructor : 'Lara Omar',
        level : 'LEV.1',
        degree : '80/100',
    },
    {
        id:2,
        date : 'Friday,june 7th',
        time : '12:00 AM',
        courseName:'Introduction To React',
        instructor : 'Karim Omar',
        level : 'LEV.2',
        degree : '50/100',
    },
    {
        id:3,
        date : 'Monday,Mars 7th',
        time : '1:30 PM',
        courseName:'Introduction Javascript',
        instructor : 'Sara Mohamed',
        level : 'LEV.5',
        degree : '70/100',
    },
    {
        id:4,
        date : 'Saturday,Novmber 11th',
        time : '10:30 AM',
        courseName:'Introduction CSS',
        instructor : 'Omar Seif',
        level : 'LEV.1',
        degree : '100/100',
    },
    {
        id:5,
        date : 'Wednesday,june 7th',
        time : '3:30 PM',
        courseName:'Introduction HTML',
        instructor : 'Lara Omar',
        level : 'LEV.1',
        degree : '80/100',
    },
    {
        id:6,
        date : 'Friday,june 1th',
        time : '12:00 AM',
        courseName:'Introduction Bootstrap',
        instructor : 'Nermeen Yasser',
        level : 'LEV.3',
        degree : '60/100',
    },
    {
        id:7,
        date : 'Monday,Mars 4th',
        time : '1:25 PM',
        courseName:'Introduction CSS3',
        instructor : 'Sarah Ali',
        level : 'LEV.2',
        degree : '85/100',
    },
    {
        id:8,
        date : 'Wednesday,june 7th',
        time : '12:30 PM',
        courseName:'Introduction  HTML5',
        instructor : 'Tamer Mohsen',
        level : 'LEV.1',
        degree : '80/100',
    },
    {
        id:9,
        date : 'Thruthday,July 3th',
        time : '9:45 AM',
        courseName:'Introduction Jquery',
        instructor : 'Ahmed Ezz',
        level : 'LEV.1',
        degree : '100/100',
    },
    {
        id:10,
        date : 'Friday,june 7th',
        time : '12:00 AM',
        courseName:'Introduction Database',
        instructor : 'Hend Omar',
        level : 'LEV.2',
        degree : '90/100',
    },
    {
        id:11,
        date : 'Saturday,April 9th',
        time : '3:45 PM',
        courseName:'Introduction Asp.Net',
        instructor : 'Mostafa Fathy',
        level : 'LEV.5',
        degree : '65/100',
    },
    {
        id:12,
        date : 'Sunday,May 5th',
        time : '2:35 PM',
        courseName:'Introduction Node.js',
        instructor : 'Tariq Ahmed',
        level : 'LEV.2',
        degree : '80/100',
    },
]

